# -*- coding: utf-8 -*-
"""A_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcrHoRZWFNVT1n3MEeXDJj0zDhGRG5eD
"""

import heapq

graph = {
    "Lahore": {"Rawalpindi": 290, "Faisalabad": 150},
    "Rawalpindi": {"Lahore": 290, "Peshawar": 180},
    "Faisalabad": {"Lahore": 150, "Multan": 210},
    "Multan": {"Faisalabad": 210, "Karachi": 920},
    "Peshawar": {"Rawalpindi": 180},
    "Karachi": {"Multan": 920}
}

heuristic = {
    "Lahore": 1300,
    "Rawalpindi": 1150,
    "Faisalabad": 1080,
    "Multan": 920,
    "Peshawar": 1250,
    "Karachi": 0
}

def a_star(graph, start, goal, heuristic):
    open_list = []
    heapq.heappush(open_list, (heuristic[start], [start]))
    g_costs = {start: 0}
    closed_set = set()

    while open_list:
        f, path = heapq.heappop(open_list)
        node = path[-1]

        if node == goal:
            return path, g_costs[node]

        if node in closed_set:
            continue

        closed_set.add(node)

        for neighbor, cost in graph[node].items():
            tentative_g = g_costs[node] + cost

            if neighbor not in g_costs or tentative_g < g_costs[neighbor]:
                g_costs[neighbor] = tentative_g
                f_cost = tentative_g + heuristic.get(neighbor, float('inf'))
                new_path = path + [neighbor]
                heapq.heappush(open_list, (f_cost, new_path))

    return None, float('inf')

if __name__ == "__main__":
    start_city = "Lahore"
    goal_city = "Karachi"
    path, cost = a_star(graph, start_city, goal_city, heuristic)
    print("A* path:", path)
    print("Total cost:", cost)